---
title: "Tema 3 - Distribuciones Notables: resumen de cada distribución"
author: "Probabilidad con R y python"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  beamer_presentation: 
    includes:
      in_header: header_pagenrs_complet.tex
    theme: CambridgeUS
    slide_level: 2
  ioslides_presentation:
    css: Mery_style.css
    keep_md: yes
    logo: Images/matriz_mov.gif
    widescreen: yes
    output:
  slidy_presentation:
    incremental: no
lang: es-ES
linkcolor: green
classoption: aspectratio=169 
---



```{r setup0, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
library(reticulate)
```

## Resumen v.a con distribución binomial $B(n,p)$

\renewcommand{\arraystretch}{1.75}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X$ binomial:   $B(n,p)$ \\\hline
$\scriptstyle  D_X=   \{0,1,\ldots n\}$  \\\hline
$\scriptstyle P_X(x)=P(X=x)=\left\{\begin{array}{ll}\scriptstyle {n\choose x}\cdot  p^x\cdot  (1-p)^{n-x} & \mbox{ si } x=0,1,\ldots,n\\0  & \mbox{ en otro caso.}\end{array}\right.$ \\\hline
$\scriptstyle  F_X(x)=P(X\leq X)=
\scriptstyle\left\{
\begin{array}{ll}
\scriptstyle  0 & \scriptstyle  \mbox{ si } x<0\\ 
\scriptstyle \sum_{i=0}^k {n\choose i}\cdot  p^i\cdot  (1-p)^{n-i} &  
\scriptstyle \mbox{si } \scriptstyle k\leq x< k+1 \mbox{\small para } \scriptstyle k=0,1,\dots,n \\ 
\scriptstyle 1 & \scriptstyle  \mbox{ si } x\geq n
\end{array}
\right.$.\\\hline
$\scriptstyle E(X)=n\cdot p$; $\scriptstyle  Var(X)=n\cdot p \cdot (1-p)$ \\\hline
\end{tabular}
\end{table}


## Cálculos binomial con R

Sea $X$ con distribución  binomial  $B(n=10,p=0.25)$. 

* `dbinom(0,size=10,prob=0.25) ` : $P_X(0)=P(X=0).$ 

* `pbinom(4,size=10,prob=0.25) ` : $F_X(4)=P(X\leq 4).$ 

* `qbinom(0.91,size=10,prob=0.25) `:  Cuantil $0.91$  $P(X\leq x_{0.91})\geq 0.91$. 

* `rbinom(100,size=10,prob=0.25) `: Muestra aleatoria de tamaño de una Binomial. 


## Resumen  distribución geométrica $Ge(p)$ empezando en 0

\renewcommand{\arraystretch}{1.75}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X=$ Geométrica (empieza en $0$) número de fracasos  para conseguir el primer éxito
\\\hline
$D_X=\{0,1,\ldots n,\ldots\}$ \\\hline
$P_X(x)=P(X=x)=\left\{\begin{array}{ll}(1-p)^{x}\cdot p & \mbox{ si } x=0,1,2,\ldots \\0  & \mbox{ en otro caso.}\end{array}\right.$\\\hline
$F_X(x)=P(X\leq X)=\left\{\begin{array}{ll} 0 & \mbox{ si } x<0\\
  1- (1-p)^{k+1} & \mbox{ si } \left\{ \begin{array}{l}k\leq x< k+1\\\mbox{para } k=0,1,2,\ldots\end{array}
    \right.\end{array}\right.$ \\\hline
$E(X)=\frac{1-p}{p}$; $Var(X)=\frac{1-p}{p^2}$\\\hline
\end{tabular}
\end{table}


## Resumen distribución geométrica $Ge(p)$ empezando en $1$.

\renewcommand{\arraystretch}{1.75}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$Y$ geométrica (que cuenta el éxito) número de \blue{INTENTOS}  para OBTENER el primer éxito
\\\hline
$D_Y=\{1,2,\ldots n,\ldots\}$ \\\hline
$P_Y(y)=P(Y=y)=\left\{\begin{array}{ll}(1-p)^{y-1}\cdot p & \mbox{ si } y=1,2,3,\ldots\\  0  & \mbox{ en otro caso.}\end{array}\right.$\\\hline
$F_Y(y)=P(Y\leq y)=\left\{\begin{array}{ll} 0 & \mbox{ si } y<1\\ 1- (1-p)^{k} & \mbox{ si } \left\{ \begin{array}{l}k\leq y< k+1\\\mbox{para } k=1,2,3,\dots \end{array}    \right.\end{array}\right.$ \\\hline
$E(X)=\frac1{p}; Var(X)=\frac{1-p}{p^2}$
\\\hline
\end{tabular}
\end{table}


## Cálculos geométrica con R


Sea $X$ con distribución   geométrica  $Ge(p=0.25)$. 

* `dgeom(0,prob=0.25) ` : $P_X(0)=P(X=0).$ 

* `pgeom(4,prob=0.25) ` : $F_X(4)=P(X\leq 4).$ 

* `qgeom(0.91,prob=0.25) `:  Cuantil $0.91$  $P(X\leq x_{0.91})\geq 0.91$. 

* `rgeom(100,prob=0.25) `: Muestra aleatoria  de tamaño de una  Geométrica.

* \blue{Propiedad de la falta  de memoria} $P\left(X> k+j\big| X\geq j\right)=P(X> k)$ para todo $k,j=0,1,2,3\ldots$.


## Resumen distribución  Binomial Negativa $BN(n,p)$

\renewcommand{\arraystretch}{1.8}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
 $X=$ Número de fracasos antes de conseguir el $n$-ésimo éxito, $P(\mbox{Éxito})=p$. $BN(n,p)$ 
\\\hline
$D_X=\{0,1,2,3\ldots\}$  \\\hline
$P_X(k)=P(X=k)=\left\{\begin{array}{ll} {k+n-1\choose n-1} \cdot (1-p)^{k}\cdot p^n, & \mbox{si }  k=0,1,\ldots \\ 0, & \mbox{en otro caso.}\end{array}\right.$\\\hline
$
F_X(x)=P(X\leq x)=
\left\{
\begin{array}{ll} 0, & \mbox{si } x<0\\\displaystyle\sum_{i=0}^{k} P(X=i) & \mbox{si  }\left\{\begin{array}{l}k\leq x< k+1,\\k=0,1,2,\ldots\end{array}\right.\end{array}\right.$ 
\\\hline
$E(X)=n\cdot\frac{1-p}{p}$;  $Var(X)=n\cdot \frac{1-p}{p^2}.$ \\\hline
\end{tabular}
\end{table}

## Cálculos distribución binomial negativa con R

Sea  $X$  una variable aleatoria  $BN(n=2,p=0.1)$.

* `dnbinom(0,size=2,prob=0.25) ` : $P_X(0)=P(X=0).$ 

* `pnbinom(4,size=2,prob=0.25) ` : $F_X(4)=P(X\leq 4).$ 

* `qnbinom(0.91,size=2,prob=0.25) `:  Cuantil $0.91$  $P(X\leq x_{0.91})\geq 0.91$. 

* `rnbinom(100,size=2,prob=0.25) `: Muestra aleatoria de tamaño de una  Binomial Negativa. 




## Resumen distribución  Poisson  $X\equiv Po(\lambda)$

\renewcommand{\arraystretch}{1.75}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X$ con distribución  Poisson  de media o promedio $\lambda$,  $Po(\lambda)$
\\\hline
$D_X=\{0,1,\ldots \}$ \\\hline
$P_X(x)=P(X=x)=\left\{\begin{array}{ll}  \frac{\lambda^x}{x!}e^{-\lambda} & \mbox{ si } x=0,1,\ldots\\ 0  & \mbox{ en otro caso.}\end{array}\right.$\\\hline
$\scriptstyle F_X(x)=P(X\leq X)=\left\{\begin{array}{ll} 0 & \mbox{si } x<0\\\displaystyle\scriptstyle\sum_{i=0}^{k} P(X=i)= \displaystyle\scriptstyle\sum_{i=0}^{k} \frac{\lambda^i}{i!}\cdot e^{-\lambda} & \mbox{si  }\left\{\begin{array}{l}\scriptstyle k\leq x< k+1\\\scriptstyle k=0,1,2,\ldots\end{array}\right.\end{array}\right.$
     \\\hline
$E(X)=\lambda$; $Var(X)=\lambda$\\\hline
\end{tabular}
\end{table}


## Resumen proceso   Poisson  $X_t\equiv Po(\lambda\cdot t)$


\renewcommand{\arraystretch}{1.75}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X_t=$ número de eventos en el intervalo $(0,t]$  $Po(\lambda\cdot t)$  donde  $\lambda$ promedio por u.t. 
\\\hline
$D_X=\{0,1,\ldots \}$ \\\hline
$P_X(x)=P(X=x)=\left\{\begin{array}{ll}  \frac{(\lambda\cdot t)^x}{x!}e^{-\lambda\cdot t} & \mbox{ si } x=0,1,\ldots\\ 0  & \mbox{ en otro caso.}\end{array}\right.$\\\hline
$\scriptstyle F_X(x)=P(X\leq X)=\left\{\begin{array}{ll} 0 & \mbox{si } x<0\\\displaystyle\scriptstyle\sum_{i=0}^{k} P(X=i)= \displaystyle\scriptstyle\sum_{i=0}^{k} \frac{(\lambda\cdot t)^i}{i!}\cdot e^{-\lambda\cdot t} & \mbox{si  }\left\{\begin{array}{l}\scriptstyle k\leq x< k+1\\\scriptstyle k=0,1,2,\ldots\end{array}\right.\end{array}\right.$

   \\\hline
$E(X)=\lambda\cdot t$; $Var(X)=\lambda\cdot t$\\\hline
\end{tabular}
\end{table}


## Cálculos de la distribución Poisson con R

Sea  $X$  una variable aleatoria  $Po(\lambda=10).$.

* `dpois(0,lambda=10) ` : $P_X(0)=P(X=0).$ 

* `ppois(4,lambda=10) ` : $F_X(4)=P(X\leq 4).$ 

* `qpois(0.91,lambda=10) `:  Cuantil $0.91$  $P(X\leq x_{0.91})\geq 0.91$. 

* `rpois(100,lambda=10) `: Muestra aleatoria   de tamaño 100 de una  Poisson.









## Resumen distribución   Hipergeométrica  $H(m,n,k)$.

\renewcommand{\arraystretch}{1.75}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X= \left\{\begin{array}{l}
\mbox{número de bolas blancas  en $k$ extracciones}\\
\mbox{sin reposición de una urna con} $m$\\
\mbox{bolas blancas y }$n$ \mbox{ negras.}
\end{array}\right.$;  $H(m,n,k)$
\\\hline
$D_X=\left\{x\in\mathbb{N}\mid \max\{0,k-n\}\leq  x \leq \min\{m,k\}\right\}$\\\hline
$P_X(x)=P(X=x)=\left\{
\begin{array}{ll}
\frac{\binom{m}{x}\cdot \binom{n}{k-x}}{\binom{m+n}{k}}, & \mbox{ si }
\max\{0,k-n\}\leq x \leq \min\{m,k\}, \\
0,  & \mbox{en otro caso.}\end{array}\right.$\\\hline
$F_X(x)=P(X\leq x)$.\\\hline
$E(X)=\frac{k\cdot m}{m+n}$; $Var(X)=k\cdot\frac{m}{m+n}\cdot\left(1-\frac{m}{m+n}\right) \cdot\frac{m+n-k}{m+n-1}$
\\\hline
\end{tabular}
\end{table}




## Cálculos distribución Hipergeométtrica con R



Sea $X$ una v.a. $H(m=15,n=10,k=3)$. La función de `R`

* `dhyper(0,m=15,10,k=3)`  : $P_X(0)=P(X=0).$ 

* `phyper(4,m=15,10,k=3) ` : $F_X(4)=P(X\leq 4).$ 

* `qhyper(0.91,m=15,10,k=3) `:  Cuantil $0.91$  $P(X\leq x_{0.91})\geq 0.91$. 

* `rhyper(100,m=15,10,k=3)`: Muestra aleatoria  de tamaño 100 de una Hypergeometrica.



## Resumen v.a con distribución uniforme, $U(a,b)$

\renewcommand{\arraystretch}{1.8}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
Distribución uniforme $U(a,b)$
\\\hline
Dominio $D_X=(a,b)$\\\hline
$f_{X}(x)\left\{\begin{array}{ll}\frac1{b-a}, & \mbox{si } a<x<b,\\ 0,  & \mbox{en cualquier otro caso.}\end{array} \right.$\\\hline
$F_X(x)=P(X\leq X)=\left\{\begin{array}{ll} 0, & \mbox{ si } x\leq a\\\frac{x-a}{b-a}, & \mbox{ si } a\leq x\leq b,\\1, & \mbox{ si } b\leq x.\end{array}\right.$\\\hline
$E(X)=\frac{a+b}2$; $Var(X)=\frac{(b-a)^2}{12}$
\\\hline
\end{tabular}
\end{table}



## Cálculos distribución uniforme con   R

Sea $X$ una $v.a.$ $U(a=-1,b=-1)$.

* Por defecto los parámetros son  `min=0` y `max=1`.

* `dunif(0,min=-1,max=1)`  : $f_X(0).$ 

* `punif(4,min=-1,max=1) ` : $F_X(4)=P(X\leq 4).$ 

* `qunif(0.91,min=-1,max=1) `:  Cuantil $0.91$  $P(X\leq x_{0.91})= 0.91$. 

* `runif(100,min=-1,max=1) `: Muestra aleatoria  de tamaño 100 de una uniforme.


## Resumen v.a con distribución exponencial, $Exp(\lambda)$


\renewcommand{\arraystretch}{2}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X$ sigue una distribución $Exp(\lambda)$
\\\hline
$D_X=(0,+\infty)$ \\\hline
$f_{X}(x)=\left\{\begin{array}{ll} \lambda\cdot  e^{-\lambda x} & \mbox{ si }  x>0\\ 0 & \mbox{ si } x\leq 0 \end{array}\right.$
\\\hline
$F_X(x)=P(X\leq X)= \left\{\begin{array}{ll} 0 &\mbox{si } x\leq 0\\1-e^{-\lambda x}& \mbox{si } x>0\end{array}\right.$
\\\hline
$E(X)=\frac{1}{\lambda}$; $Var(X)=\frac{1}{\lambda^2}$
\\\hline
\end{tabular}
\end{table}


## Cálculos distribución exponencial con   R

Sea $X$ una $v.a.$ $Exp(\lambda=3)$.

* La $\lambda=3$ es el parámetro `rate`.

* `dexp(0,rate=3)`  : $f_X(0)).$ 

* `pexp(4,rate=3) ` : $F_X(4)=P(X\leq 4).$ 

* `qexp(0.91,rate=3) `:  Cuantil $0.91$  $P(X\leq x_{0.91})= 0.91$. 

* `rexp(100,rate=3) `: Muestra aleatoria  de tamaño 100 de una exponencial.



## Resumen v.a con distribución normal, $N(\mu,\sigma)$


\renewcommand{\arraystretch}{2}
\begin{table}
\centering
\begin{tabular}{|l|}
\hline\rowcolor{LightBlue}
$X$  sigue una distribución $N(\mu,\sigma)$ \\\hline
$D_X=\mathbb{R}=(-\infty,+\infty)$\\\hline
$f_{X}(x)=\frac{1}{\sqrt{2\pi\cdot\sigma^2}}\cdot e^{\frac{-(x-\mu)^2}{2\cdot \sigma^2}}\mbox{ para todo }x\in \mathbb{R}.$\\\hline
$\displaystyle F_X(x)=P(X\leq X)=\int_{-\infty}^x f_X(t) dt.$\\\hline
$E(X)=\mu$;  $Var(X)=\sigma^2.$
\\\hline
\end{tabular}
\end{table}

## Cálculos distribución normal con   R

Sea $X$ una $v.a.$ normal $N(\mu=1.\sigma=2)$. Los parámetros son `mean` para $\mu$ y `sd` para $\sigma$

*  Los parámetros por defecto son `mean=0, `sd=1`, es decir, los de la normal estándar.

* `dnorm(0,mean=0,sd=1)`  : $f_X(0).$ 

* `pnorm(4,mean=0,sd=1) ` : $F_X(4)=P(X\leq 4).$ 

* `qnorm(0.91,mean=0,sd=1) `:  Cuantil $0.91$  $P(X\leq x_{0.91})= 0.91$. 

* `rnorm(100,mean=0,sd=1) `: Muestra aleatoria  de tamaño 100 de una normal.

