---
title: "Ejercicios Tema 3 Parte 1 - Distribuciones Notables: discretas."
author: "Distribuciones notables discretas"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  pdf_document:
    number_sections: yes
    toc: true
    toc_depth: 2
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: '2'
linkcolor: red
header-includes: \renewcommand{\contentsname}{Contenidos}
citecolor: blue
toccolor: blue
urlcolor: blue 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
num=0
```


# Distribuciones notables discretas



## Problema `r num=num+1;num`. 

Se lanzan a la vez 5 dados (de parchís)  bien balanceados. Sea $X$ el número  
de unos que  se observan en la  cara superior del dado.
Calcular la esperanza de $X$, la varianza de  $X$,
$P(1\leq X<4)$ y $P(X\geq 2).$ 

## Problema `r num=num+1;num`.

El  10\% de los usb fabricados por una marca tienen algún defecto (pero son baratos). Si se seleccionan al azar 10 de los usb  fabricados por esta fábrica, ¿cuáles la probabilidad  de que ninguno sea defectuoso? ¿Cuántos usb defectuosos debemos esperar?

## Problema `r num=num+1;num`.

Si $Y$ sigue una distribución  binomial con media
$\mu_Y=6$ y varianza $\sigma_Y^2=4$. Calcular  la distribución de $Y$, es decir, encontrad los valores de  $n$ y $p$.

## Problema `r num=num+1;num`.

Un fabricante de *bombillas inteligentes*  controladas por *Bluetooth* las vende a sus distribuidores  en lotes de 20. Supongamos que la probabilidad de que una bombillas inteligentes esté defectuosa es del  $0.05$. 

1. ¿Cuál es el número esperado de bombillas defectuosas por paquete.
2. ¿Cuál  es la probabilidad de  que un determinado lote  no
tenga ninguna bombilla  defectuosa?

## Problema `r num=num+1;num`.

Una urna contiene 10 bolas, una de color negro  y las demás blancas. Sea $Z$ el número de extracciones con reposición necesarias para extraer la bola negra. ¿Cuál es la  distribución  de la variable  $Z$? 

## Problema `r num=num+1;num`.

Se lanza una moneda al aire hasta que sale  cara. Supongamos que cada  tirada es independiente  de las otras y que la probabilidad de que salga  cara cada vez es $p$.  

1.  Demostrar que la probabilidad de que hagan falta un número impar de lanzamientos es ${p\over 1-q^2}$ donde $q=1-p$. 
2.  Encontrar  el valor de $p$ tal que la probabilidad de que  necesitemos un número impar de intentos sea $0.6$.
3.  ¿Existe un valor de $p$ tal que la probabilidad de que haga falta un número impar de intentos sea $0.5$?

## Problema `r num=num+1;num`.

Se ha observado que el aforo  medio de  vehículos  en un determinado paso  de un camino rural es de 3 coches/hora.
Suponer que los instantes en que pasan automóviles son independientes. Sea
$X$ el número de coches  que pasas por este lugar  en un  intervalo de 20 minutos, modelizar la distribución de $X$ con una distribución notable discreta.
Calcular $P(X=0)$ y $P(X\geq 2)$.


## Problema `r num=num+1;num`.

La proporción de niños pelirrojos es 1  cada 10.000. En una gran ciudad  se produjeron 5.000
nacimientos en 2020, aproximar por la distribución de Poisson la probabilidad
que ninguno  de los nacidos ese año sea pelirrojo. Aproximar
la probabilidad de que nazca  exactamente 1 niño pelirrojo y  la de que hayan
nacido al menos 2 pelirrojos.

## Problema `r num=num+1;num`.

Un  vendedor de vehículos usados utiliza la  web ComproMotos. Supongamos que el número de ventas  sigue un proceso de Poisson  de  parámetro $\lambda =1$ vehículo  por semana.

1. ¿Cuál es la probabilidad que haya exactamente 3 ventas en un periodo de 2
semanas? 
2. ¿Y  como mínimo  3 ventas?  ¿Y cómo máximo 3 ventas?
3. ¿Cuál es la probabilidad de que pasen 3 periodos de   2 semanas consecutivas sin ventas?

## Problema `r num=num+1;num`.

Lanzamos un moneda hasta que obtenemos como mínimo  3 caras y 3 cruces. Encontrar la probabilidad de que el juego no se acabe en 10  lanzamientos.

